/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
static yyconst short int yy_acclist[311] =
    {   0,
       77,   77,   82,   81,   75,   81,   36,   81,   35,   81,
       53,   81,   54,   81,   60,   81,   59,   81,   64,   81,
       62,   81,   69,   81,   61,   81,   77,   78,   79,   81,
       65,   81,   73,   81,   63,   81,   72,   81,   77,   81,
       42,   77,   81,   39,   77,   81,   40,   77,   81,   55,
       77,   81,   56,   77,   81,   34,   77,   81,   77,   81,
       77,   81,   77,   81,   77,   81,   77,   81,   41,   77,
       81,   77,   81,   77,   81,   77,   81,   77,   81,   77,
       81,   77,   81,   37,   77,   81,   77,   81,   77,   81,
       38,   77,   81,   77,   81,   77,   81,   57,   81,   58,

       81,   80,   78,   79,   67,   68,   78,   76,   79,   77,
       78,   77,   77,   79,   46,   77,   44,   77,   50,   77,
       48,   77,   77,   70,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   45,   77,   77,   77,   77,   43,   77,
       77,   20,   77,   77,   22,   77,   77,   77,   77,   26,
       77,   77,   77,   49,   77,   77,   77,   47,   77,   77,
       77,   77,   77,   77,   78,    4,   77,   77,   77,   77,
       77,   77,   77,   11,   77,   12,   77,   77,   77,   77,
       77,   77,   77,   17,   77,   77,   77,   77,   77,   77,
       77,   77,   25,   77,   77,   77,   77,   77,   77,   77,

       30,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   13,   77,   14,   77,   77,   77,   77,   18,
       77,   77,   77,   71,   77,   77,   77,    2,   77,   77,
       27,   77,   77,   77,   77,   77,    3,   77,   77,   32,
       77,   77,   77,    6,   77,    7,   77,    8,   77,    9,
       77,   77,   77,   77,    1,   77,   77,   77,   77,   77,
       77,   77,   66,   77,   28,   77,   77,   77,   31,   77,
       33,   77,    5,   77,   77,   77,   15,   77,   16,   77,
       19,   77,   21,   77,   23,   77,   77,   77,   29,   77,
       77,   77,   74,   77,   77,   77,   77,   10,   77,   77,

       24,   77,   77,   77,   77,   52,   77,   77,   51,   77
    } ;

static yyconst short int yy_accept[211] =
    {   0,
        1,    2,    3,    4,    5,    7,    9,   11,   13,   15,
       17,   19,   21,   23,   25,   27,   31,   33,   35,   37,
       39,   41,   44,   47,   50,   53,   56,   59,   61,   63,
       65,   67,   69,   72,   74,   76,   78,   80,   82,   84,
       87,   89,   91,   94,   96,   98,  100,  102,  103,  103,
      105,  106,  107,  108,  109,  110,  112,  113,  115,  117,
      119,  121,  123,  124,  126,  127,  128,  129,  130,  131,
      132,  133,  134,  136,  137,  138,  139,  141,  142,  144,
      145,  147,  148,  149,  150,  152,  153,  154,  156,  157,
      158,  160,  161,  162,  163,  164,  165,  166,  166,  168,

      169,  170,  171,  172,  173,  174,  176,  178,  179,  180,
      181,  182,  183,  184,  186,  187,  188,  189,  190,  191,
      192,  193,  195,  196,  197,  198,  199,  200,  201,  203,
      204,  205,  206,  207,  208,  209,  210,  211,  212,  213,
      215,  217,  218,  219,  220,  222,  223,  224,  226,  227,
      228,  230,  231,  233,  234,  235,  236,  237,  239,  240,
      242,  243,  244,  246,  248,  250,  252,  253,  254,  255,
      257,  258,  259,  260,  261,  262,  263,  265,  267,  268,
      269,  271,  273,  275,  276,  277,  279,  281,  283,  285,
      287,  288,  289,  291,  292,  293,  295,  296,  297,  298,

      300,  301,  303,  304,  305,  306,  308,  309,  311,  311
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    4,    1,    1,    1,    1,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,    1,    1,   20,   20,   20,   20,   20,   21,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   22,   20,   20,   23,   20,   20,   20,   20,   20,
       24,   20,   25,   20,   26,   20,   27,   28,   29,   30,

       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   20,   43,   44,   45,   46,   20,   47,   48,
       49,   20,   50,    1,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[52] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    2,
        1,    2,    1,    2,    1,    2,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        1
    } ;

static yyconst short int yy_base[211] =
    {   0,
        0,    0,  180,  163, 1149,  144,  140,  137,  134,  105,
       40,  103,   41,   46,  101,   58,   97,   89,   87,   86,
       61,   66,   80,   88,   96,  104,  112,  115,   86,   94,
      105,   99,  141,  104,  125,   40,  126,  131,  150,  168,
      158,  163,  114,  179,  181,   81,   79, 1149,   75,  208,
     1149, 1149,   72,   65,   75,  221,  224,  229,  239,  244,
      247,  258,  259,  232,  250,  251,  269,  264,  283,  285,
      270,  291,  302,  303,  308,  317,  318,  328,  323,  337,
      338,  350,  355,  360,  370,  371,  385,  372,  387,  393,
      405,  407,  419,  420,  430,  440,   51,   72,  441,  442,

      453,  463,  474,  462,  475,  483,  488,  497,  508,  518,
      520,  510,  526,  531,  540,  553,  545,  558,  566,  574,
      585,  575,  580,  593,  595,  601,  610,  612,  618,  628,
      630,  644,  653,  663,  664,  678,  655,  689,  673,  690,
      700,  710,  711,  722,  723,  732,  737,  745,  757,  755,
      766,  767,  772,  777,  787,  789,  799,  807,  809,  819,
      825,  834,  836,  842,  844,  852,  854,  869,  874,  884,
      886,  894,  899,  909,  907,  921,  926,  932,  941,  942,
      943,  951,  953,  959,  968,  976,  978,  986,  988,  994,
     1003, 1013, 1005, 1011, 1023, 1021, 1043, 1048, 1032, 1053,

     1058, 1064, 1066, 1083, 1075, 1091, 1093, 1101, 1149,   64
    } ;

static yyconst short int yy_def[211] =
    {   0,
      209,    1,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  210,  209,  209,  209,  209,
      210,  210,  210,  210,  210,  210,  210,  210,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  210,  210,  210,  210,  210,
      210,  210,  210,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,  209,  209,   28,   28,

       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,

       28,   28,   28,   28,   28,   28,   28,   28,    0,  209
    } ;

static yyconst short int yy_nxt[1201] =
    {   0,
        4,    5,    4,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,    4,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   21,   35,   21,   21,   36,   21,   37,
       38,   39,   40,   41,   42,   43,   44,   21,   45,   46,
       47,   49,   49,   50,   50,   48,   48,   51,   52,   53,
       54,   48,   49,  209,   97,   57,   82,   55,  209,   49,
      209,   56,  209,   48,   54,  209,   48,  209,   98,   57,
       83,   48,  209,   57,   55,   53,   57,   59,   53,  209,
      209,  209,   58,   58,   48,   48,   48,  209,  209,  209,

       61,   48,   48,   48,   48,  209,  209,  209,   60,   55,
       55,   48,   48,  209,  209,  209,   48,  209,   48,   48,
       48,  209,   62,  209,  209,   57,  209,   48,   66,   57,
       48,   67,   57,   57,   68,   69,   71,   57,   57,   70,
       57,   78,   57,   57,   57,   57,   72,   57,   57,   48,
       57,   57,   48,   57,   63,   48,   79,   57,   64,   48,
       57,   65,   73,   80,   81,   57,   84,   74,   57,   57,
       57,   57,   57,   85,   57,   75,   86,   57,   48,  209,
       57,   76,  209,   77,   57,  209,  209,   57,   88,   57,
      209,   92,   87,   57,   89,  209,   57,   57,   90,   91,

      209,   57,   57,  209,   57,   93,   57,   57,  209,   57,
      209,   57,   94,   95,   57,   96,  209,   55,   57,   49,
       57,   97,   57,  209,   57,   57,  209,   57,  209,  209,
      209,  209,   49,  209,   56,  209,  209,  209,   55,  209,
      209,  209,   55,   55,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,   58,   58,  209,  209,  209,  209,  209,
      209,   57,  209,  209,  209,  100,  102,  209,   57,  209,
      101,  103,  209,  209,  209,  209,  209,  209,   99,   57,
       57,  209,  209,   57,   57,  104,   57,   57,  209,  209,

      209,  209,  209,  105,  109,  209,  209,   57,   57,   57,
       57,  108,   57,  110,  106,   57,   57,  209,  209,  111,
      107,  209,   57,  209,   57,  209,   57,  209,   57,   57,
       57,   57,  209,  209,   57,  209,  209,   57,  209,  209,
      112,   57,   57,  209,  209,   57,   57,  113,   57,   57,
      209,   57,  209,  209,   57,  209,   57,   57,  115,  114,
       57,   57,   57,   57,   57,  209,   57,   57,  116,   57,
      209,   57,  118,  209,   57,  209,   57,   57,  117,  209,
       57,   57,  209,   57,   57,  209,  209,  209,  119,   57,
      209,  209,  209,   57,  120,  209,   57,  209,   57,  121,

      209,   57,  209,   57,  122,  209,   57,  209,  209,   57,
       57,   57,  209,   57,  123,   57,   57,   57,   57,  124,
      209,  125,  209,  209,   57,  209,   57,  209,   57,  209,
       57,   57,   57,   57,  209,  209,   57,  126,  209,   57,
      209,  209,  209,  209,   57,  209,   57,  127,   57,  209,
       57,   57,  209,   57,  130,  209,  209,  209,   57,   57,
      209,  209,   57,   57,  128,   57,   57,  129,  209,   57,
      132,  209,  133,   57,  131,  209,   57,  209,  209,   57,
       57,   57,  209,   57,   57,   57,   57,   57,   57,  209,
      209,  209,  134,  209,  209,  209,   57,  135,  209,   57,

      136,   57,   57,  209,  209,  137,   57,  209,   57,   57,
      209,  209,  209,   57,   57,  209,  209,   57,   57,  138,
       57,   57,   57,  209,  209,  209,   57,   57,  139,   57,
      209,   57,  209,  209,   57,  209,   57,  209,  209,  140,
       57,  209,  209,   57,  209,  209,  209,   57,  141,   57,
      142,   57,  144,  143,   57,  209,   57,   57,  209,   57,
      209,   57,  209,   57,   57,   57,   57,  209,  209,   57,
       57,  209,   57,  209,   57,  209,  209,   57,  145,   57,
      146,  209,  209,   57,   57,  147,   57,  209,   57,  209,
      209,   57,   57,  149,  209,  209,   57,   57,  209,   57,

      209,   57,  148,  209,   57,   57,  150,  209,  209,   57,
      209,  209,   57,   57,   57,  151,  209,   57,   57,   57,
       57,   57,  152,  153,   57,  209,   57,  209,   57,  209,
      209,   57,  154,  209,   57,  209,   57,  209,  155,   57,
       57,   57,  158,  209,   57,  209,  156,   57,  209,   57,
      209,   57,  157,   57,  209,   57,   57,   57,   57,  209,
      209,   57,  209,  160,   57,  159,  209,   57,  209,   57,
      209,   57,  209,   57,   57,  209,   57,  209,  209,  209,
      209,  161,  209,   57,  209,  209,  209,   57,  209,  209,
       57,  163,   57,  209,   57,  162,   57,  209,  166,   57,

      209,   57,   57,   57,  209,  209,   57,   57,  164,   57,
       57,  209,   57,  168,  165,  209,   57,   57,  209,   57,
      209,   57,  209,  167,   57,  209,  209,  209,   57,   57,
      209,  209,   57,   57,  209,   57,   57,  209,  209,   57,
      209,  170,  209,   57,  209,  209,   57,  209,  209,   57,
       57,  169,  209,   57,   57,  209,   57,   57,  172,  171,
      209,   57,   57,  209,  209,   57,   57,  209,   57,   57,
      209,   57,  209,  209,  209,   57,   57,  209,   57,  173,
       57,  209,  209,   57,   57,  209,  174,  209,   57,  209,
      209,   57,  209,  209,   57,  209,   57,  209,  175,  209,

       57,   57,  209,   57,  209,   57,   57,  176,  209,   57,
       57,   57,   57,   57,  209,   57,   57,  178,   57,  209,
       57,  177,  209,   57,  209,  209,   57,  209,   57,  209,
       57,  179,   57,   57,  209,   57,  209,  209,   57,  181,
      209,  209,   57,  180,  209,   57,   57,  209,   57,  209,
       57,  209,   57,   57,  182,   57,  209,  209,   57,  209,
      209,  209,   57,  209,   57,   57,  209,  209,   57,  209,
      209,   57,  209,   57,  209,   57,  209,   57,  183,   57,
       57,   57,   57,   57,  209,   57,  209,   57,   57,  209,
       57,   57,  209,  184,  209,   57,  209,   57,   57,  209,

       57,  209,  209,  209,  209,  209,  209,  209,   57,  209,
      209,  185,   57,   57,  209,   57,  209,   57,  186,  209,
       57,  209,  209,   57,  209,   57,  209,   57,  209,   57,
       57,  188,   57,   57,  187,  190,  209,   57,   57,  209,
       57,  209,   57,  189,  209,   57,   57,  209,   57,  192,
       57,  191,   57,   57,  209,   57,  209,  209,  209,  209,
       57,  209,  209,  209,   57,   57,  209,   57,  209,   57,
      209,   57,   57,  209,  209,   57,  209,  209,   57,  209,
      193,   57,   57,  209,   57,  194,   57,   57,   57,   57,
       57,  209,   57,  209,   57,  209,   57,   57,   57,   57,

      209,  209,   57,  209,  195,   57,  209,   57,  196,  209,
      209,   57,  209,  209,   57,   57,  209,   57,  209,   57,
      209,   57,   57,  209,   57,   57,  209,   57,  209,   57,
      209,   57,   57,   57,   57,  209,  209,   57,  209,  198,
       57,  209,   57,  209,   57,  197,   57,  209,   57,   57,
       57,   57,   57,  200,   57,  199,   57,   57,  209,   57,
       57,  209,   57,  209,   57,  209,   57,   57,  209,   57,
      209,   57,  209,  209,  203,   57,  209,  201,   57,  209,
      209,  209,   57,  209,  209,  202,   57,   57,  209,   57,
      209,   57,   57,  209,   57,  209,   57,  204,  209,   57,

      205,   57,  209,   57,   57,   57,  209,   57,  209,   57,
       57,  209,   57,  209,  207,  206,  209,  209,   57,  209,
      209,   57,   57,  209,  209,  208,   57,  209,  209,   57,
       57,  209,   57,  209,   57,  209,   57,   57,  209,   57,
       57,  209,  209,  209,   57,  209,  209,   57,    3,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209

    } ;

static yyconst short int yy_chk[1201] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   11,   13,   11,   13,   11,   13,   11,   13,   14,
       16,   14,   97,   21,   97,  210,   36,   16,   22,   16,
       21,   16,   21,   16,   98,   22,   21,   22,   54,   36,
       36,   22,   23,   36,   55,   53,   36,   22,   49,   23,
       24,   23,   16,   16,   47,   23,   46,   24,   25,   24,

       23,   20,   19,   24,   18,   25,   26,   25,   22,   55,
       55,   25,   17,   26,   27,   26,   15,   28,   12,   26,
       10,   27,   23,   27,   28,   29,   28,   27,   29,   29,
       28,   30,   29,   30,   30,   31,   32,   30,   32,   31,
       30,   34,   32,   34,   31,   32,   32,   34,   31,    9,
       34,   31,    8,   43,   28,    7,   35,   43,   28,    6,
       43,   28,   33,   35,   35,   37,   37,   33,   35,   37,
       38,   35,   37,   38,   38,   33,   39,   38,    4,    3,
       33,   33,    0,   33,   33,    0,    0,   33,   40,   39,
        0,   41,   39,   39,   40,    0,   39,   41,   40,   40,

        0,   41,   42,    0,   41,   42,   42,   40,    0,   42,
        0,   40,   44,   44,   40,   45,    0,   50,   44,   50,
       45,   50,   44,   56,   45,   44,   57,   45,    0,    0,
       56,   58,   56,   57,   56,   57,   56,    0,   58,   57,
       58,   59,   50,   50,   58,    0,   60,   64,   59,   61,
       59,    0,    0,   60,   59,   60,   61,    0,   61,   60,
       62,   63,   61,   58,   58,   65,   66,   62,   63,   62,
       63,   64,    0,   62,   63,   64,   65,    0,   64,   68,
       64,   66,    0,    0,   67,   71,    0,    0,   63,   65,
       66,    0,    0,   65,   66,   67,   65,   66,   69,    0,

       70,    0,    0,   68,   71,    0,   72,   68,   67,   71,
       68,   70,   67,   71,   69,   67,   71,   73,   74,   72,
       69,    0,   69,   75,   70,    0,   69,    0,   70,   69,
       72,   70,   76,   77,   72,    0,    0,   72,   79,    0,
       74,   73,   74,   78,    0,   73,   74,   75,   73,   74,
        0,   75,   80,   81,   75,    0,   76,   77,   77,   76,
       76,   77,   79,   76,   77,   82,   79,   78,   78,   79,
       83,   78,   81,    0,   78,   84,   80,   81,   80,    0,
       80,   81,    0,   80,   81,   85,   86,   88,   82,   82,
        0,    0,    0,   82,   83,    0,   82,    0,   83,   84,

       87,   83,   89,   84,   84,    0,   84,    0,   90,   85,
       86,   88,    0,   85,   86,   88,   85,   86,   88,   87,
       91,   89,   92,    0,   87,    0,   89,    0,   87,    0,
       89,   87,   90,   89,   93,   94,   90,   90,    0,   90,
        0,    0,    0,    0,   91,   95,   92,   92,   91,    0,
       92,   91,    0,   92,   94,   96,   99,  100,   93,   94,
        0,    0,   93,   94,   93,   93,   94,   93,  101,   95,
       96,    0,  100,   95,   95,    0,   95,  104,  102,   96,
       99,  100,    0,   96,   99,  100,   96,   99,  100,  103,
      105,    0,  101,    0,    0,    0,  101,  102,  106,  101,

      103,  104,  102,  107,    0,  104,  102,    0,  104,  102,
        0,    0,  108,  103,  105,    0,    0,  103,  105,  105,
      103,  105,  106,  109,    0,  112,  106,  107,  108,  106,
        0,  107,    0,  110,  107,  111,  108,    0,    0,  109,
      108,  113,    0,  108,    0,    0,  114,  109,  110,  112,
      111,  109,  113,  112,  109,  115,  112,  110,    0,  111,
      117,  110,    0,  111,  110,  113,  111,    0,  116,  113,
      114,    0,  113,  118,  114,    0,    0,  114,  115,  115,
      116,  119,    0,  115,  117,  117,  115,    0,  117,  120,
      122,  117,  116,  119,    0,  123,  116,  118,    0,  116,

      121,  118,  118,    0,  118,  119,  120,    0,  124,  119,
      125,    0,  119,  120,  122,  121,  126,  120,  122,  123,
      120,  122,  121,  123,  121,  127,  123,  128,  121,    0,
        0,  121,  124,  129,  125,    0,  124,    0,  125,  124,
      126,  125,  128,  130,  126,  131,  126,  126,    0,  127,
        0,  128,  127,  127,    0,  128,  127,  129,  128,  132,
        0,  129,    0,  131,  129,  130,    0,  130,  133,  131,
      137,  130,    0,  131,  130,    0,  131,    0,  134,  135,
        0,  132,    0,  132,    0,    0,    0,  132,  139,    0,
      132,  134,  133,  136,  137,  133,  133,    0,  137,  133,

        0,  137,  134,  135,  138,  140,  134,  135,  135,  134,
      135,    0,  139,  139,  136,  141,  139,  136,    0,  139,
        0,  136,    0,  138,  136,  142,  143,    0,  138,  140,
        0,    0,  138,  140,    0,  138,  140,  144,  145,  141,
        0,  143,    0,  141,    0,    0,  141,  146,    0,  142,
      143,  142,  147,  142,  143,    0,  142,  143,  146,  144,
      148,  144,  145,    0,    0,  144,  145,    0,  144,  145,
      150,  146,  149,    0,    0,  146,  147,    0,  146,  147,
      147,  151,  152,  147,  148,    0,  149,  153,  148,    0,
        0,  148,  154,    0,  150,    0,  149,    0,  150,    0,

      149,  150,  155,  149,  156,  151,  152,  152,    0,  151,
      152,  153,  151,  152,  157,  153,  154,  155,  153,    0,
      154,  154,  158,  154,  159,    0,  155,    0,  156,    0,
      155,  156,  156,  155,  160,  156,    0,    0,  157,  159,
      161,    0,  157,  157,    0,  157,  158,    0,  159,  162,
      158,  163,  159,  158,  161,  159,    0,  164,  160,  165,
        0,    0,  160,    0,  161,  160,    0,  166,  161,  167,
        0,  161,    0,  162,    0,  163,    0,  162,  162,  163,
      162,  164,  163,  165,  168,  164,    0,  165,  164,  169,
      165,  166,    0,  167,    0,  166,    0,  167,  166,  170,

      167,  171,    0,    0,    0,    0,    0,    0,  168,  172,
        0,  168,  168,  169,  173,  168,    0,  169,  169,    0,
      169,    0,  175,  170,  174,  171,    0,  170,    0,  171,
      170,  172,  171,  172,  171,  174,  176,  172,  173,    0,
      172,  177,  173,  173,    0,  173,  175,  178,  174,  176,
      175,  175,  174,  175,    0,  174,  179,  180,  181,    0,
      176,    0,    0,    0,  176,  177,  182,  176,  183,  177,
        0,  178,  177,    0,  184,  178,    0,    0,  178,    0,
      179,  180,  181,  185,  179,  180,  181,  179,  180,  181,
      182,  186,  183,  187,  182,    0,  183,  182,  184,  183,

        0,  188,  184,  189,  184,  184,    0,  185,  185,  190,
        0,  185,    0,    0,  185,  186,    0,  187,  191,  186,
      193,  187,  186,    0,  187,  188,  194,  189,  192,  188,
        0,  189,  188,  190,  189,    0,  196,  190,  195,  192,
      190,    0,  191,    0,  193,  191,  191,  199,  193,  191,
      194,  193,  192,  195,  194,  194,  192,  194,  197,  192,
      196,    0,  195,  198,  196,    0,  195,  196,  200,  195,
        0,  199,    0,  201,  199,  199,    0,  197,  199,  202,
        0,  203,  197,    0,    0,  198,  197,  198,    0,  197,
      205,  198,  200,    0,  198,    0,  200,  201,  204,  200,

      203,  201,    0,  202,  201,  203,  206,  202,  207,  203,
      202,    0,  203,    0,  205,  204,  208,    0,  205,    0,
        0,  205,  204,    0,    0,  207,  204,    0,    0,  204,
      206,    0,  207,    0,  206,    0,  207,  206,    0,  207,
      208,    0,    0,    0,  208,    0,    0,  208,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  209,  209

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "projflex.l"
#define INITIAL 0
#line 2 "projflex.l"

#include "y.tab.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
void yyerror (char *s);
int yylex();

#line 756 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 17 "projflex.l"



#line 922 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 210 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1149 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 20 "projflex.l"
{return FALSE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 21 "projflex.l"
{return NONE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 22 "projflex.l"
{return TRUE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 23 "projflex.l"
{return AND;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 24 "projflex.l"
{return ASSERT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 25 "projflex.l"
{return ASYNC;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 26 "projflex.l"
{return AWAIT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 27 "projflex.l"
{return BREAK;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 28 "projflex.l"
{return CLASS;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 29 "projflex.l"
{return CONTINUE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 30 "projflex.l"
{return DEF;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 31 "projflex.l"
{return DEL;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 32 "projflex.l"
{return ELIF;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 33 "projflex.l"
{return ELSE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 34 "projflex.l"
{return EXCEPT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 35 "projflex.l"
{return FINALY;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 "projflex.l"
{return FOR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 37 "projflex.l"
{return FROM;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 38 "projflex.l"
{return GLOBAL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 39 "projflex.l"
{return IF;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 40 "projflex.l"
{return IMPORT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 41 "projflex.l"
{return IN;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 43 "projflex.l"
{return LAMBDA;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 44 "projflex.l"
{return NONLOCAL;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 45 "projflex.l"
{return NOT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 46 "projflex.l"
{return OR;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 47 "projflex.l"
{return PASS;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 48 "projflex.l"
{return RAISE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "projflex.l"
{return RETURN;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 "projflex.l"
{return TRY;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 51 "projflex.l"
{return WHILE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 "projflex.l"
{return WITH;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "projflex.l"
{return YIELD;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 54 "projflex.l"
{return KATWPAVLA;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 "projflex.l"
{return QUOTE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "projflex.l"
{return DOUBLEQUOTE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "projflex.l"
{return r;} 
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "projflex.l"
{return u;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "projflex.l"
{return R;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "projflex.l"
{return U;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "projflex.l"
{return f;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "projflex.l"
{return F;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "projflex.l"
{return fr;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "projflex.l"
{return Fr;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 65 "projflex.l"
{return fR;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 66 "projflex.l"
{return FR;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 67 "projflex.l"
{return rf;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 68 "projflex.l"
{return Rf;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 69 "projflex.l"
{return rF;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 70 "projflex.l"
{return RF;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 71 "projflex.l"
{return SHORTSTRING;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 72 "projflex.l"
{return LONGSTRING;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 73 "projflex.l"
{return LEFTBRACKET;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 74 "projflex.l"
{return RIGHTBRACKET;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 75 "projflex.l"
{return LSQUAREBRACKET;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 76 "projflex.l"
{return RSQUAREBRACKET;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 77 "projflex.l"
{return CURLLEFT;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 78 "projflex.l"
{return CURLRIGHT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 79 "projflex.l"
{return PLUS;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 80 "projflex.l"
{return MUL;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 81 "projflex.l"
{return DIVISION;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 82 "projflex.l"
{return MINUS;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 83 "projflex.l"
{return ISON;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 84 "projflex.l"
{return KOMMA;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 85 "projflex.l"
{return ANWKATWTELEIA;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 86 "projflex.l"
{return PRINT;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 87 "projflex.l"
{return SINISON;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 88 "projflex.l"
{return PLINISON;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 89 "projflex.l"
{return TELEIA;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 90 "projflex.l"
{return AS;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 91 "projflex.l"
{return INIT;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 92 "projflex.l"
{return MEGALUTERO;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 93 "projflex.l"
{return MIKROTERO;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 94 "projflex.l"
{return DIAFORO;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 97 "projflex.l"
{}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 107 "projflex.l"
{return INTEGER;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 108 "projflex.l"
{return IDENTIFIER;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 109 "projflex.l"
{return FLOATNUMBER;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 110 "projflex.l"
{return IMAGINUMBER;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 111 "projflex.l"

	YY_BREAK
case 81:
YY_RULE_SETUP
#line 112 "projflex.l"
ECHO;
	YY_BREAK
#line 1418 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 210 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 210 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 209);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 112 "projflex.l"
